2022-04-05 / 23:52:03  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 00:07:01  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 00:40:54  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 02:48:01  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 02:49:20  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 12:49:51  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 13:10:40  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: name 'model' is not defined
2022-04-06 / 13:11:47  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-06 / 13:20:11  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-07 / 23:29:45  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-07 / 23:30:23  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-07 / 23:34:29  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-07 / 23:36:02  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\Predictions_using_trained_model.py'>
2022-04-08 / 00:18:13  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\app.py'>
2022-04-08 / 00:19:35  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\app.py'>
2022-04-08 / 00:20:07  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\app.py'>
2022-04-08 / 00:20:56  ----->  Exception occurred while predicting the mushroom category using the saved models. Exception: Can't get attribute 'ModelWithSameOutputEverytime' on <module '__main__' from 'C:\\Users\\shiva\\Desktop\\Mushroom classification\\Mushroom_Classification\\src\\app.py'>
2022-04-08 / 11:07:40  ----->  Prediction results placed at the path: Prediction_Output_File\Predictions.csv
2022-04-08 / 19:35:09  ----->  Prediction results placed at the path: Prediction_Output_File\Predictions.csv
2022-04-08 / 19:46:29  ----->  Prediction results placed at the path: Prediction_Output_File\Predictions.csv
2022-04-08 / 21:45:48  ----->  Prediction results placed at the path: Prediction_Output_File\Predictions.csv
2022-04-08 / 21:46:39  ----->  Prediction results placed at the path: Prediction_Output_File\Predictions.csv
2022-04-08 / 21:48:02  ----->  Prediction results placed at the path: Prediction_Output_File\Predictions.csv
